In [3]:
import numpy as np

# Exercise 4: Random Data Generation

# 1. Set the seed to 888
np.random.seed(888)

# 2. Generate a one-dimensional array of size 100 with normal distribution
normal_1d = np.random.randn(100)
print("1D normal array shape:", normal_1d.shape)
print()

# 3. Generate a two-dimensional array of size 8,8 with random integers from 1 to 10
random_2d = np.random.randint(1, 11, (8, 8))
print("2D uniform array shape:", random_2d.shape)
print("2D array:\n", random_2d)
print()

# 4. Generate a three-dimensional array of size 4,2,5 with random integers from 1 to 17
random_3d = np.random.randint(1, 18, (4, 2, 5))
print("3D uniform array shape:", random_3d.shape)
print("3D array:\n", random_3d)

1D normal array shape: (100,)

2D uniform array shape: (8, 8)
2D array:
 [[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]

3D uniform array shape: (4, 2, 5)
3D array:
 [[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]
