In [2]:
import numpy as np

# Exercise 6: Broadcasting and Slicing

# 1. Generate a 2-dimensional array of size 9x9, with all elements initialized to 1 and of type int8
array_9x9 = np.ones((9, 9), dtype=np.int8)
print("1. 9x9 array initialized to 1 (int8):")
print(array_9x9)
print()

# 2. Using slicing, create the pattern array
# Start with the ones array and modify specific regions using slicing
pattern_array = np.ones((9, 9), dtype=np.int8)

# Create the border pattern by setting inner regions to 0
pattern_array[1:8, 1:8] = 0  # Inner 7x7 region to 0
pattern_array[2:7, 2:7] = 1  # Inner 5x5 region back to 1  
pattern_array[3:6, 3:6] = 0  # Inner 3x3 region to 0
pattern_array[4, 4] = 1      # Center cell to 1

print("2. Pattern array created using slicing:")
print(pattern_array)
print()

# 3. Using broadcasting to create output matrix
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)

# Broadcasting: array_1 is (5,) and array_2 is (3,)
# Reshape array_1 to (5,1) to broadcast with array_2 (3,)
# Result will be (5,3) matrix
broadcast_result = array_1.reshape(-1, 1) * array_2

print("3. Broadcasting result:")
print("array_1:", array_1)
print("array_2:", array_2)
print("Broadcast multiplication result:")
print(broadcast_result)

1. 9x9 array initialized to 1 (int8):
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]

2. Pattern array created using slicing:
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]

3. Broadcasting result:
array_1: [1 2 3 4 5]
array_2: [1 2 3]
Broadcast multiplication result:
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]
