In [1]:
import numpy as np
import itertools

# Exercise 9: Football Tournament

# Load the forecast matrix from file
try:
    forecasts = np.loadtxt('model_forecasts.txt')
    print("Loaded forecasts from model_forecasts.txt")
except FileNotFoundError:
    print("model_forecasts.txt not found, creating sample data...")
    # Create sample data as fallback
    np.random.seed(42)
    forecasts = np.random.randint(-5, 6, size=(10, 10))
    np.fill_diagonal(forecasts, 0)
    for i in range(10):
        for j in range(i+1, 10):
            forecasts[j, i] = -forecasts[i, j]

print("Model forecasts matrix (10x10):")
print(forecasts)
print()

# Generate all possible pairings (permutations of teams 0-9)
teams = list(range(10))
all_permutations = list(itertools.permutations(teams))

print(f"Total permutations to evaluate: {len(all_permutations)}")

# Convert permutations to numpy array for vectorized operations
perms_array = np.array(all_permutations)

# For each permutation, calculate the sum of squared differences
# Teams are paired as: (perm[0], perm[1]), (perm[2], perm[3]), ..., (perm[8], perm[9])
team1_indices = perms_array[:, ::2]  # Even indices: 0, 2, 4, 6, 8
team2_indices = perms_array[:, 1::2]  # Odd indices: 1, 3, 5, 7, 9

# Get score differences for each pairing using advanced indexing
score_diffs = forecasts[team1_indices, team2_indices]

# Calculate sum of squared differences for each permutation
squared_diffs = score_diffs ** 2
sum_squared_diffs = np.sum(squared_diffs, axis=1)

# Find the permutation with minimum sum of squared differences
best_permutation_idx = np.argmin(sum_squared_diffs)
best_permutation = all_permutations[best_permutation_idx]
best_score = sum_squared_diffs[best_permutation_idx]

print(f"Best permutation index: {best_permutation_idx}")
print(f"Best sum of squared differences: {best_score}")
print(f"Best permutation: {best_permutation}")
print()

# Format output as required: [[team1s], [team2s]]
matches_team1 = [best_permutation[i] for i in range(0, 10, 2)]
matches_team2 = [best_permutation[i] for i in range(1, 10, 2)]

result = np.array([matches_team1, matches_team2])

print("Optimal pairing result:")
print("[[m1_t1 m2_t1 m3_t1 m4_t1 m5_t1]")
print(" [m1_t2 m2_t2 m3_t2 m4_t2 m5_t2]]")
print()
print("Result:")
print(result)
print()

# Show the matches and their predicted differences
print("Match details:")
for i in range(5):
    t1, t2 = matches_team1[i], matches_team2[i]
    diff = forecasts[t1, t2]
    print(f"Match {i+1}: Team {t1} vs Team {t2}, Predicted difference: {diff}, Squared: {diff**2}")

print(f"\nTotal sum of squared differences: {best_score}")

model_forecasts.txt not found, creating sample data...
Model forecasts matrix (10x10):
[[ 0 -2  5  2 -1  1  4 -3  1  5]
 [ 2  0 -1 -2  2  2 -3  0 -1 -4]
 [-5  1  0 -1 -5  4  0  3 -5  5]
 [-2  2  1  0 -2  3 -3 -1 -3  1]
 [ 1 -2  5  2  0  3 -4  4  3  4]
 [-1 -2 -4 -3 -3  0 -5 -2 -4  2]
 [-4  3  0  3  4  5  0 -4  4 -4]
 [ 3  0 -3  1 -4  2  4  0 -1  2]
 [-1  1  5  3 -3  4 -4  1  0  2]
 [-5  4 -5 -1 -4 -2  4 -2 -2  0]]

Total permutations to evaluate: 3628800
Best permutation index: 122428
Best sum of squared differences: 7
Best permutation: (0, 4, 1, 5, 2, 6, 3, 9, 7, 8)

Optimal pairing result:
[[m1_t1 m2_t1 m3_t1 m4_t1 m5_t1]
 [m1_t2 m2_t2 m3_t2 m4_t2 m5_t2]]

Result:
[[0 1 2 3 7]
 [4 5 6 9 8]]

Match details:
Match 1: Team 0 vs Team 4, Predicted difference: -1, Squared: 1
Match 2: Team 1 vs Team 5, Predicted difference: 2, Squared: 4
Match 3: Team 2 vs Team 6, Predicted difference: 0, Squared: 0
Match 4: Team 3 vs Team 9, Predicted difference: 1, Squared: 1
Match 5: Team 7 vs Team 8, Pr