In [1]:
import numpy as np

rng = np.random.default_rng(888)         # seed 888

# 1D normal (size 100) — standard normal (mean 0, std 1)
one_d_normal = rng.standard_normal(100)
print(one_d_normal.shape)

# 8x8 uniform integers from 1 to 10 inclusive
arr_8_8 = rng.integers(1, 11, size=(8, 8))
print(arr_8_8)

# 4 x 2 x 5 integers 1..17 inclusive
arr_4_2_5 = rng.integers(1, 18, size=(4, 2, 5))
print(arr_4_2_5.shape)


(100,)
[[ 4 10  4  2  2  1  3  4]
 [ 7  2  7  6  6 10  3  3]
 [10  9  9  7  9  5  9 10]
 [ 9  4  6 10 10 10  7  7]
 [ 5  5  7  3  8  5  7  3]
 [ 4  4  7 10  2 10  4  8]
 [ 2  8  7  2  2  6  5  4]
 [ 4  8  8  8  5  1  5  2]]
(4, 2, 5)
